workflows:
  build_flutter_apk:
    name: Build Flutter APK
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        BUILD_MODE: "apk"
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK (debug)
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
